### ISSUE TITLE
hi,shamilnabiyev

### ISSUE THREAD

**Issue by ShiinoMashiro** [shamilnabiyev/alfa-uav-fault-detection#1]
the method read_data() in data-processing.ipynb uses column 'timestamp' , but there is no column named 'timestamp' in  my dataset ALFA downloaded from website. I am wondering if i had downloaded the wrong dataset or there's something wrong or missed somewhere. 
Your advice would be helpful to me. thanks.

**Comment by shamilnabiyev** [comment]
Hi @ShiinoMashiro, thanks for opening an issue. The issue has been fixed and the `data-processing.ipynb` should work now.  Please, check it again.

**Comment by licj1** [comment]
> the method read_data() in data-processing.ipynb uses column 'timestamp' , but there is no column named 'timestamp' in my dataset ALFA downloaded from website. I am wondering if i had downloaded the wrong dataset or there's something wrong or missed somewhere. Your advice would be helpful to me. thanks.

Hello, do you also research this dataset? Can we have a discussion? could you please send me your email or other contacts? Thank you!

**Comment by ShiinoMashiro** [comment]
> > the method read_data() in data-processing.ipynb uses column 'timestamp' , but there is no column named 'timestamp' in my dataset ALFA downloaded from website. I am wondering if i had downloaded the wrong dataset or there's something wrong or missed somewhere. Your advice would be helpful to me. thanks.
> 
> Hello, do you also research this dataset? Can we have a discussion? could you please send me your email or other contacts? Thank you!

Hi,you can contact me through yaojun@nuaa.edu.cn ,I wish we could together research this dataset。

**Comment by shamilnabiyev** [comment]
Hey @licj1 @ShiinoMashiro I'm afraid, I'm not using this dataset for my research anymore. It was just my first attempt to understand the data.

**Comment by ShiinoMashiro** [comment]
At least you have helped me understand the data😊，thanks bro.



发自我的iPhone


------------------ Original ------------------
From: Shamil Nabiyev ***@***.***&gt;
Date: Wed,Nov 2,2022 6:40 PM
To: shamilnabiyev/alfa-uav-fault-detection ***@***.***&gt;
Cc: ShiinoMashiro ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [shamilnabiyev/alfa-uav-fault-detection] hi,shamilnabiyev (Issue #1)





 
Hey @licj1 @ShiinoMashiro I'm afraid, I'm not using this dataset for my research anymore. It was just my first attempt to understand the data.
